import type { ParseIssue, ParseResult, RouteDefinition } from '@/types/route'
import { extractRoutesFromText, finalizeRoute } from './routeParser'

function detectDuplicates(routes: RouteDefinition[], issues: ParseIssue[]): void {
  const seen = new Map<string, string[]>()
  for (const route of routes) {
    for (const method of route.methods.length ? route.methods : ['<unknown>']) {
      const key = `${method} ${route.path}`
      const list = seen.get(key) ?? []
      list.push(route.id)
      seen.set(key, list)
    }
  }
  for (const [key, ids] of seen) {
    if (ids.length > 1) {
      for (const id of ids) {
        issues.push({ level: 'warning', message: `Duplicate route detected: "${key}" appears ${ids.length} times.`, routeId: id })
      }
    }
  }
}

const TICKET_EXTERNAL_HINT_RE = /\b(external gw|gw-ext|ext-gw|\[ext\]|external)\b/i
const TICKET_KONG_HINT_RE = /\b(kong deck|deck|kong-ce)\b/i

/** Parse a full Jira ticket description into normalized routes, split by external/excluded status. */
export function parseTicket(text: string): ParseResult {
  const issues: ParseIssue[] = []

  if (!text.trim()) {
    return { routes: [], excludedRoutes: [], issues: [] }
  }

  const extracted = extractRoutesFromText(text)

  const routes: RouteDefinition[] = []
  const excludedRoutes: RouteDefinition[] = []

  for (const item of extracted) {
    const route = finalizeRoute(item, !item.excluded, issues)
    if (route.excluded) {
      excludedRoutes.push(route)
    } else {
      routes.push(route)
    }
  }

  detectDuplicates(routes, issues)

  if (TICKET_EXTERNAL_HINT_RE.test(text)) {
    issues.push({ level: 'info', message: 'Ticket references an external gateway context (External GW / GW-EXT / EXT-GW).' })
  }
  if (TICKET_KONG_HINT_RE.test(text)) {
    issues.push({ level: 'info', message: 'Ticket mentions Kong Deck / decK — both Format A and Format B are still generated by default.' })
  }
  if (routes.length === 0 && excludedRoutes.length === 0) {
    issues.push({ level: 'warning', message: 'No API routes were detected in this ticket. Try adjusting the text or check the example tickets.' })
  }

  return { routes, excludedRoutes, issues }
}
